// Error Categories - 126 total
const ERROR_CATEGORIES = [
    "ACU-Embedded/Non Embedded",
    "ACU-Incorrect Year/Contract/Member Worked",
    "ACU-ODS/LITES OOS",
    "ACU-Retro Change",
    "BEN-Authorization",
    "BEN-Benefits - Services Paid/Not Paid",
    "BEN-Benefits Maximum/Accum",
    "COB -Comments not loaded to file",
    "COB- Flags and/or med notes not updated/not updated correctly",
    "COB- letter not sent",
    "COB- Number of Employees Not Verified",
    "COB- Working Status Not Verified",
    "COB-Effective/Term Date Incorrect",
    "COB-ESRD not updated",
    "COB-Impacted claims adjusted incorrectly",
    "COB-Impacted claims not adjusted",
    "COB-Incorrect letter sent",
    "COB-Member not added to watch list",
    "COB-Member update incomplete",
    "COB-OC Employer Omitted",
    "COB-OC Group Number Omitted",
    "COB-OC Name",
    "COB-Payment/Cost Savings Incorrect",
    "COB-Policy ID#",
    "COB-Primacy Order Incorrect Commercial",
    "COB-Primacy Order Incorrect Medicare",
    "COD-Data Incorrect/Missing",
    "COD-Dental Downgrade",
    "COD-Dental PPD",
    "COD-Dental Tooth",
    "COD-Pricing Method & Rule NonFinancial",
    "COD-Type of Service",
    "ELG-Group Active/Inactive",
    "ELG-Member Eligibility",
    "MDOC-Missing Group Documents",
    "MDOC-Missing Provider Contract",
    "OPL-Medicare",
    "OPL-Worker's Comp / Subrogation",
    "OTH-ITS BlueCard Other",
    "OTH-Other",
    "OTH-Other BCBS Plan",
    "PDM-Address",
    "PDM-Other",
    "PDM-Provider Name",
    "PDM-Provider Network",
    "PDM-Specialty/Type",
    "PDM-TIN/NPI#",
    "PEC-Provider Contract/Agreement",
    "PEC-Provider Reimbursement/Discount",
    "PENDING-Awaiting Benefits",
    "PENDING-Awaiting Provider Contract",
    "PMT-Dental Ctrl #",
    "PMT-Dental Rules Bypass",
    "PMT-Dental Waiting Period",
    "PMT-DME-Rental to Purchase",
    "PMT-Duplicate - Approved in Error",
    "PMT-Duplicate - Denied in Error",
    "PMT-Interest Calculation Incorrect",
    "PMT-ITS DF & Pmt/Reimb Mismatch",
    "PMT-ITS Invalid DF / DF Mismatched",
    "PMT-Late Charges",
    "PMT-Line Charge",
    "PMT-Member Liability - Penalty/Sanction",
    "PMT-Member Liability (OOP) - Coinsurance",
    "PMT-Member Liability (OOP) - Copay",
    "PMT-Member Liability (OOP) - Deductible",
    "PMT-Mom & Baby",
    "PMT-Paid In-/Out-of-Network",
    "PMT-Patient Incorrect",
    "PMT-Payee Incorrect",
    "PMT-Split Claim",
    "PMT-Timely Filing",
    "PMT-Transplant Related",
    "PMT-Voided Claim",
    "PRC-Ambulance",
    "PRC-Ambulatory Surgery Center (ASC)",
    "PRC-Anesthesia",
    "PRC-Carve Outs",
    "PRC-Clinical Edit",
    "PRC-Contract/Rate Sheet Load",
    "PRC-Critical Access",
    "PRC-Diagnostics",
    "PRC-DME",
    "PRC-DRG",
    "PRC-Drugs",
    "PRC-ESRD",
    "PRC-Global Rate",
    "PRC-Home Health",
    "PRC-ITS Allowed Amount",
    "PRC-Manual Other",
    "PRC-Mental Health",
    "PRC-Method & Rule",
    "PRC-Multiple Surgeries",
    "PRC-NOC",
    "PRC-Observation Room",
    "PRC-Outpatient",
    "PRC-Per Diem",
    "PRC-Rural Health",
    "PRC-SNF",
    "PRC-Stoploss",
    "PRC-Systems Other",
    "PRC-Vision",
    "SYS-System",
    "VND-Out of Scope (Vendor Only)",
    "WRK-Addl Info (Needed/Not Used)",
    "WRK-Adjustment Incorrect/Incomplete",
    "WRK-Adjustment Reason Code",
    "WRK-Claim Note Text",
    "WRK-Denial Code",
    "WRK-Dental DRU",
    "WRK-Documentation/Workflow",
    "WRK-EOB Message Code",
    "WRK-EOB Status/Suppress EOB",
    "WRK-Incorrect Letter Info and/or Letter Format",
    "WRK-IQT Closed/Routed in Error",
    "WRK-ITS Handle Direct",
    "WRK-Medicaid",
    "WRK-Medicare",
    "WRK-Misrouted",
    "WRK-MRU Guidelines",
    "WRK-Pre-existing",
    "WRK-Prompt Pay/Interest Date",
    "WRK-Provider ID",
    "WRK-Reduction/Type Code",
    "WRK-Type Code"
];
